export interface Project {
  title: string;
  date: string;
  description: string;
  url: string;
  image: string;
  techs: string[];
  website?: string | null;
  source: string;
}

export const projects: Project[] = [
  {
    title: "Secure Learn",
    date: "June 2025",
    description: "Concepts of encryption & decryption.",
    url: "https://github.com/ReintB/secure-learn",
    image: "/projects/secureLearn.png",
    techs: ["Next.js", "React.js", "Typescript", "TailwindCSS", "Shadcn/UI"],
    website: "https://secure-learn.vercel.app/",
    source: "https://github.com/ReintB/secure-learn",
  },
  {
    title: "Scanalyze",
    date: "June 2025",
    description: "Analyze documents with AI.",
    url: "https://github.com/ReintB/scanalyze",
    image: "/projects/scanalyze.png",
    techs: [
      "Next.js",
      "React.js",
      "Typescript",
      "TailwindCSS",
      "Shadcn/UI",
      "PostgreSQL",
    ],
    website: "https://scanalyze-sepia.vercel.app/",
    source: "https://github.com/ReintB/scanalyze",
  },
  {
    title: "XIIPALINGTEKNIK",
    date: "March 2025",
    description: "Class 2024/2025 Website.",
    url: "https://github.com/ReintB/xiipalingteknik",
    image: "/projects/kelas.png",
    techs: ["Next.js", "React.js", "Typescript", "TailwindCSS", "Shadcn/UI"],
    website: "https://www.xiipalingteknik.site/",
    source: "https://github.com/ReintB/xiipalingteknik",
  },
  {
    title: "Tebak Baku",
    date: "April 2025",
    description: "Standard Indonesian Word Quiz.",
    url: "https://github.com/ReintB/TebakBaku",
    image: "/projects/tebakBaku.png",
    techs: [
      "Next.js",
      "React.js",
      "Typescript",
      "TailwindCSS",
      "Radix UI",
      "ESLint",
    ],
    website: "https://tebakbaku.vercel.app/",
    source: "https://github.com/ReintB/TebakBaku",
  },
  {
    title: "REGO",
    date: "March 2025",
    description: "ReImaginate Further With REGO!",
    url: "https://github.com/ReintB/rego",
    image: "/projects/rego.png",
    techs: ["React.js", "Bootstrap", "AOS", "Swiper", "Vite"],
    website: "https://rego-gamma.vercel.app/",
    source: "https://github.com/ReintB/rego",
  },
  {
    title: "Book App",
    date: "June 2025",
    description: "Book App with Google Books API.",
    url: "https://github.com/ReintB/book-app",
    image: "/projects/bookApp.png",
    techs: ["React.js", "Bootstrap", "Vite", "Google Books API"],
    website: "https://book-app-lac-alpha.vercel.app/",
    source: "https://github.com/ReintB/book-app",
  },
  {
    title: "Album Finder",
    date: "June 2025",
    description: "App to search for an artist & view their albums.",
    url: "https://github.com/ReintB/AlbumFinder",
    image: "/projects/albumFinder.png",
    techs: ["React.js", "Bootstrap", "Vite", "Spotify API"],
    website: "https://album-finder-cyan.vercel.app/",
    source: "https://github.com/ReintB/AlbumFinder",
  },
  {
    title: "Groq Birth Facts",
    date: "June 2025",
    description: "AI-powered birth date fact generator.",
    url: "https://github.com/ReintB/groq-birth-facts",
    image: "/projects/projects.png",
    techs: ["HTML", "CSS", "Python", "Flask", "Groq"],
    website: null,
    source: "https://github.com/ReintB/groq-birth-facts",
  },
  {
    title: "Tic-Tac-Toe React",
    date: "June 2025",
    description: "Follow the tic-tac-toe react tutorial.",
    url: "https://github.com/ReintB/tic-tac-toe-react",
    image: "/projects/ticTacToe.png",
    techs: ["React.js", "Bootstrap", "Vite"],
    website: "https://tic-tac-toe-react-nine-self.vercel.app/",
    source: "https://github.com/ReintB/tic-tac-toe-react",
  },
  {
    title: "LUA Memory Game",
    date: "April 2025",
    description: "LUA Color Memory Game.",
    url: "https://github.com/ReintB/memory-game.",
    image: "/projects/projects.png",
    techs: ["Lua"],
    website: null,
    source: "https://github.com/ReintB/memory-game",
  },
  {
    title: "Mini E-Commerce",
    date: "June 2024",
    description: "Mini E-Commerce with search and filter feature.",
    url: "https://github.com/ReintB/mini-e-commerce",
    image: "/projects/miniECommerce.png",
    techs: ["React.js", "Bootstrap", "Vite"],
    website: "https://mini-e-commerce-five.vercel.app/",
    source: "https://github.com/ReintB/mini-e-commerce",
  },
];
